server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lookup_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

redis:
  host: localhost
  port: 6379
